- hosts: compute_hosts
  tasks:
  - name: Initialize some variables
    set_fact:
      migrate: false
      mysql_user: "root"
      mysql_pass: "9b70f3f9f79b7032d936b32943ce6c2400ca4fd3c679ddb00b42d3cc"
      mysql_host: "172.29.236.100"
      false_ports: []
      taps_on_bridge: []
      qbr_bridge_list: []

  - name: Gather instances from virsh
    shell: |
      virsh -q list
    register: running_instances

  - name: Check for running instances
    fail: msg="Please stop all running instances on this node"
    when: running_instances.stdout_lines|length > 0

  - name: Find all ports on a given compute node
    shell: |
      source /root/openrc
      /openstack/venvs/neutron-14.2.11/bin/neutron port-list --binding:host_id='{{container_name}}' -c 'id' -c 'binding:host_id' -c 'binding:vif_details' -f json
    register: compute_ports_json
    args:
      executable: /bin/bash

  - name: Find all ports on a given compute node whose ovs_hybrid_plug=false
    set_fact:
      false_ports: "{{ false_ports }} + [ '{{ item['id'] }}' ]"
    when: not item['binding:vif_details']['ovs_hybrid_plug']
    with_items:
      - "{{ compute_ports_json.stdout|from_json }}"

  - name: Determine whether we need to migrate on this host
    set_fact:
      "migrate": true
    when: false_ports|length > 0

  - debug: var=migrate

  - name: Stop neutron services
    service:
      name: "{{ item }}"
      state: stopped
    with_items:
    - neutron-openvswitch-agent
    when: migrate

  - name: Stop nova services
    service:
      name: "{{ item }}"
      state: stopped
    with_items:
    - nova-compute
    when: migrate

  - name: Replace firewall driver in config files
    lineinfile: dest={{ item }} regexp='^firewall_driver' line='firewall_driver = iptables_hybrid'
    with_items:
      - "/etc/neutron/plugins/ml2/ml2_conf.ini"
      - "/etc/neutron/plugins/ml2/openvswitch_agent.ini"
    when: migrate

  - name: Update ovs_hybrid_plug=true for respective Neutron ports in mysql
    shell: |
      mysql -u {{ mysql_user }} --password={{ mysql_pass }} -h {{ mysql_host }} -e "use neutron; update ml2_port_bindings set vif_details = '{\"port_filter\": true, \"ovs_hybrid_plug\": true}' where port_id='{{ item }}' limit 1;"
    with_items: false_ports
    when: migrate

  - name: Start neutron services
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
    - neutron-openvswitch-agent
    when: migrate

  - name: Start nova services
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
    - nova-compute
    when: migrate
